<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Şantiye Takip Kurulumu</title><link rel="icon" type="image/svg+xml" href="{{ asset('assets/brand-mark.svg') }}?v=20260731-1"><link rel="stylesheet" href="{{ asset('assets/app.css') }}?v=20260731-1"></head>
<body class="login-page"><main class="installer">
<section class="login-card install-card"><div class="login-brand"><img class="brand-logo login-logo" src="{{ asset('assets/brand-mark.svg') }}" alt="Şantiye Takip"><h1>Şantiye <span>Takip</span> Kurulumu</h1><p>CWP / cPanel için güvenli tek seferlik kurulum</p></div>
<h2>Sistem kontrolü</h2><ul class="requirements">@foreach($requirements as $label=>$ok)<li class="{{ $ok?'positive':'negative' }}">{{ $ok?'✓':'✕' }} {{ $label }}</li>@endforeach</ul>
@if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($ready)<form class="form-stack" method="post" action="{{ route('install.store') }}">@csrf
<h2>Site</h2><label>Site adı<input name="app_name" value="{{ old('app_name','Şantiye Takip') }}" required></label><label>Site URL’si<input type="url" name="app_url" value="{{ old('app_url',url('/')) }}" required></label>
<h2>MySQL</h2><label>Sunucu<input name="db_host" value="{{ old('db_host','localhost') }}" required></label><label>Port<input type="number" name="db_port" value="{{ old('db_port',3306) }}" required></label><label>Veritabanı<input name="db_database" value="{{ old('db_database') }}" required></label><label>Kullanıcı<input name="db_username" value="{{ old('db_username') }}" required></label><label>Veritabanı parolası<input type="password" name="db_password" autocomplete="new-password"></label>
<h2>İlk sistem yöneticisi</h2><label>Ad soyad<input name="admin_name" value="{{ old('admin_name') }}" required></label><label>Kullanıcı adı<input name="admin_username" value="{{ old('admin_username','system') }}" required></label><label>Güçlü parola<input type="password" name="admin_password" autocomplete="new-password" required></label><label>Parola tekrarı<input type="password" name="admin_password_confirmation" autocomplete="new-password" required></label>
@if($envExists)<label class="check"><input type="checkbox" name="confirm_env_backup" value="1" required> Mevcut .env dosyasının zaman damgalı yedeği alınarak güncellenmesini onaylıyorum.</label>@endif
<button class="btn primary">Bağlantıyı Test Et ve Kur</button></form>@else<p class="alert error">Eksik gereksinimler düzeltilmeden kurulum başlatılamaz.</p>@endif
</section></main></body></html>
