@extends('layouts.app')
@section('title', 'Gelişmiş Raporlar')
@section('heading', 'Gelişmiş Raporlar')
@section('content')
<div class="reports-page">
<div class="page-title"><div><h1>Kasa ve Yakıt Raporları</h1><p>Tarih, kategori, personel ve araç bazında filtreleyin.</p></div></div>
<form class="filters wrap report-filters" method="get">
<label>Başlangıç<input type="date" name="from" value="{{ request('from') }}"></label><label>Bitiş<input type="date" name="to" value="{{ request('to') }}"></label>
<label>Kategori<select name="category"><option value="">Tümü</option>@foreach($categories as $category)<option @selected(request('category')===$category)>{{ $category }}</option>@endforeach</select></label>
<label>Personel<select name="created_by"><option value="">Tümü</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(request('created_by')==$user->id)>{{ $user->name }}</option>@endforeach</select></label>
<label>Araç / Makine<select name="vehicle_id"><option value="">Tümü</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(request('vehicle_id')==$vehicle->id)>{{ $vehicle->display_name }}</option>@endforeach</select></label>
@if(auth()->user()->hasPermission('transactions.manage'))<label class="check"><input type="checkbox" name="with_deleted" value="1" @checked(request('with_deleted'))> Silinenleri dahil et</label>@endif
<button class="btn primary">Raporla</button></form>
<div class="grid two">
<section class="card table-wrap"><div class="card-head"><h2>Kasa Hareketleri</h2></div><table><thead><tr><th>Tarih</th><th>Tür</th><th>Kategori</th><th>Personel</th><th>Tutar</th></tr></thead><tbody>
@forelse($transactions as $item)<tr @class(['deleted-row' => $item->trashed()])><td>{{ $item->occurred_on->format('d.m.Y') }} @if($item->trashed())<small>Silinmiş</small>@endif</td><td>{{ $item->type==='income'?'Gelir':'Gider' }}</td><td>{{ $item->category }}<small>{{ $item->description }}</small></td><td>{{ $item->creator->name }}</td><td>{{ number_format($item->amount,2,',','.') }} ₺</td></tr>@empty<tr><td colspan="5" class="empty">Kayıt bulunamadı.</td></tr>@endforelse</tbody></table>{{ $transactions->links() }}</section>
<section class="card table-wrap"><div class="card-head"><h2>Yakıt Geçmişi</h2></div><table><thead><tr><th>Tarih</th><th>Araç</th><th>Litre</th><th>Tutar</th></tr></thead><tbody>
@forelse($fuel as $item)<tr @class(['deleted-row' => $item->trashed()])><td>{{ $item->fuel_date->format('d.m.Y') }} @if($item->trashed())<small>Silinmiş</small>@endif</td><td>{{ $item->vehicle->display_name }}</td><td>{{ number_format($item->liters,3,',','.') }}</td><td>{{ number_format($item->total_amount,2,',','.') }} ₺</td></tr>@empty<tr><td colspan="4" class="empty">Kayıt bulunamadı.</td></tr>@endforelse</tbody></table>{{ $fuel->links() }}</section>
</div>
<div class="grid two report-summary">
<section class="card table-wrap"><div class="card-head"><h2>Günlük Yakıt Toplamları</h2></div><table><thead><tr><th>Gün</th><th>Litre</th><th>Tutar</th></tr></thead><tbody>@foreach($fuelTotals as $row)<tr><td>{{ $row->period }}</td><td>{{ number_format($row->liters,3,',','.') }}</td><td>{{ number_format($row->amount,2,',','.') }} ₺</td></tr>@endforeach</tbody></table></section>
<section class="card table-wrap"><div class="card-head"><h2>Aylık Yakıt Toplamları</h2></div><table><thead><tr><th>Ay</th><th>Litre</th><th>Tutar</th></tr></thead><tbody>@foreach($monthlyFuelTotals as $row)<tr><td>{{ $row->period }}</td><td>{{ number_format($row->liters,3,',','.') }}</td><td>{{ number_format($row->amount,2,',','.') }} ₺</td></tr>@endforeach</tbody></table></section></div>
<section class="card table-wrap report-tanker-summary"><div class="card-head"><h2>Tanker Stok Özeti</h2><a href="{{ route('tankers.index') }}">Stok hareketlerine git</a></div><table><thead><tr><th>Tanker</th><th>Mevcut Stok</th><th>Son Alış Birim Maliyeti</th><th>Tahmini Stok Değeri</th></tr></thead><tbody>@forelse($tankers as $tanker)<tr><td><strong>{{ $tanker->name }}</strong></td><td>{{ number_format($tanker->stock_liters,3,',','.') }} L</td><td>{{ number_format($tanker->average_unit_cost,4,',','.') }} ₺/L</td><td>{{ number_format($tanker->stock_liters * $tanker->average_unit_cost,2,',','.') }} ₺</td></tr>@empty<tr><td colspan="4" class="empty">Aktif tanker bulunamadı.</td></tr>@endforelse</tbody></table></section>
<section class="card table-wrap report-maintenance-history"><div class="card-head"><div><h2>Araç / Makine Bakım Geçmişi</h2><small>Gider kaleminden ve bakım ekranından eklenen kayıtlar</small></div><a href="{{ route('maintenance.index', request()->only(['vehicle_id', 'from', 'to'])) }}">Bakım sayfasına git</a></div><table><thead><tr><th>Tarih</th><th>Araç / Makine</th><th>İşlem</th><th>Servis / Usta</th><th>Maliyet</th><th>Durum</th></tr></thead><tbody>@forelse($maintenance as $entry)<tr @class(['deleted-row' => $entry->trashed()])><td>{{ $entry->maintenance_date->format('d.m.Y') }} @if($entry->trashed())<small>Silinmiş</small>@endif</td><td><strong>{{ $entry->vehicle->display_name }}</strong></td><td>{{ $entry->maintenance_type }}<small>{{ $entry->description }}</small></td><td>{{ $entry->service_provider ?: '—' }}</td><td>{{ number_format($entry->cost,2,',','.') }} ₺</td><td><small>{{ $entry->transaction_id ? 'Kasaya işlendi' : 'Yalnız takip' }}</small></td></tr>@empty<tr><td colspan="6" class="empty">Seçilen filtrelerde bakım veya onarım kaydı bulunamadı.</td></tr>@endforelse</tbody></table>{{ $maintenance->links() }}</section>
<section class="card table-wrap efficiency-card"><div class="card-head"><h2>Tüketim Verimliliği</h2></div><table><thead><tr><th>Araç / Makine</th><th>Ortalama</th></tr></thead><tbody>@forelse($efficiency as $row)<tr><td>{{ $row->vehicle->display_name }}</td><td>@if($row->km_rate === null && $row->hour_rate === null)Yeterli sayaç verisi yok@else @if($row->km_rate !== null){{ number_format($row->km_rate,2,',','.') }} L/100 km @endif @if($row->hour_rate !== null)<small>{{ number_format($row->hour_rate,2,',','.') }} L/saat</small>@endif @endif</td></tr>@empty<tr><td colspan="2" class="empty">Hesaplanabilir sayaç verisi yok.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
